24-02-15 16:26:50 - root - INFO - Successfully Extracted Dataset
24-02-15 16:26:51 - root - INFO - All Standardizations are applied on Callcap data
24-02-15 16:26:51 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.7.0, Python Version: 3.11.4, Platform: Windows-10-10.0.22631-SP0
24-02-15 16:26:51 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
24-02-15 16:26:52 - snowflake.connector.cursor - INFO - query: [PUT file://C:/Users/ananya.ramesh/Phase_1/training_phase1/callcap/Data/20240215_...]
24-02-15 16:26:53 - snowflake.connector.cursor - INFO - query execution done
24-02-15 16:26:54 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 16:26:55 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 16:26:56 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 16:26:58 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 16:26:59 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 16:27:03 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 16:27:04 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 16:27:12 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 16:27:13 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 16:27:30 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 16:27:31 - root - INFO - Slack notification sent successfully!
24-02-15 16:27:31 - root - ERROR - Error: GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for exceeding maximum retries.
24-02-15 16:27:31 - snowflake.connector.connection - INFO - closed
24-02-15 16:27:31 - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session
