24-02-15 15:05:31 - root - INFO - Successfully Extracted Dataset
24-02-15 15:05:31 - root - INFO - All Standardizations are applied on Callcap data
24-02-15 15:05:31 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.7.0, Python Version: 3.11.4, Platform: Windows-10-10.0.22631-SP0
24-02-15 15:05:31 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
24-02-15 15:05:33 - snowflake.connector.cursor - INFO - query: [PUT file://C:/Users/ananya.ramesh/Phase_1/training_phase1/callcap/Data/20240215_...]
24-02-15 15:05:34 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:05:35 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:05:37 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:05:37 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:05:40 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:05:41 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:05:46 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:05:49 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:05:57 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:05:58 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:06:14 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:06:16 - root - INFO - Slack notification sent successfully!
24-02-15 15:06:16 - root - ERROR - Error: GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for exceeding maximum retries.
24-02-15 15:06:16 - snowflake.connector.connection - INFO - closed
24-02-15 15:06:16 - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session
24-02-15 15:54:19 - root - INFO - Successfully Extracted Dataset
24-02-15 15:54:19 - root - INFO - All Standardizations are applied on Callcap data
24-02-15 15:54:19 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.7.0, Python Version: 3.11.4, Platform: Windows-10-10.0.22631-SP0
24-02-15 15:54:19 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
24-02-15 15:54:20 - snowflake.connector.cursor - INFO - query: [PUT file://C:/Users/ananya.ramesh/Phase_1/training_phase1/callcap/Data/20240215_...]
24-02-15 15:54:21 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:54:22 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:54:23 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:54:24 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:54:26 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:54:27 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:54:32 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:54:35 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:54:44 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:54:45 - snowflake.connector.vendored.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])"))': /?accelerate
24-02-15 15:55:02 - snowflake.connector.storage_client - WARNING - GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for transient error: HTTPSConnectionPool(host='sfc-sg-ds1-74-customer-stage.s3.amazonaws.com', port=443): Max retries exceeded with url: /?accelerate (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', '', 'certificate verify failed')])")))
24-02-15 15:55:02 - root - INFO - Slack notification sent successfully!
24-02-15 15:55:02 - root - ERROR - Error: GET with url b'https://sfc-sg-ds1-74-customer-stage.s3.amazonaws.com/?accelerate' failed for exceeding maximum retries.
24-02-15 15:55:03 - snowflake.connector.connection - INFO - closed
24-02-15 15:55:03 - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session
24-02-15 15:58:32 - root - INFO - Successfully Extracted Dataset
24-02-15 15:58:32 - root - INFO - All Standardizations are applied on Callcap data
24-02-15 15:58:32 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.7.0, Python Version: 3.11.4, Platform: Windows-10-10.0.22631-SP0
24-02-15 15:58:32 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
24-02-15 15:58:34 - snowflake.connector.cursor - INFO - query: [PUT file://C:/Users/ananya.ramesh/Phase_1/training_phase1/callcap/Data/20240215_...]
24-02-15 15:58:35 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:58:37 - root - INFO - Loaded json data to Stage
24-02-15 15:58:37 - snowflake.connector.cursor - INFO - query: [COPY INTO staging_callcap FROM '@json_stage/20240215_15_CallCap.json.gz' FILE_FO...]
24-02-15 15:58:39 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:58:39 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
24-02-15 15:58:39 - root - INFO - Loaded json data from stage to landing table
24-02-15 15:58:39 - snowflake.connector.cursor - INFO - query: [INSERT INTO callcap (date_id, hour_id, payload) SELECT json_data:date_id::NUMBER...]
24-02-15 15:58:40 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:58:40 - root - INFO - Loaded data from Landing table to Final callcap Table
24-02-15 15:58:40 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.7.0, Python Version: 3.11.4, Platform: Windows-10-10.0.22631-SP0
24-02-15 15:58:40 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
24-02-15 15:58:41 - snowflake.connector.cursor - INFO - query: [SELECT CASE WHEN count(*)=0 THEN 'All Zipcodes are Standardized' ELSE 'Not all z...]
24-02-15 15:58:41 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:58:41 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
24-02-15 15:58:41 - root - INFO - All Zipcodes are Standardized
24-02-15 15:58:41 - snowflake.connector.cursor - INFO - query: [SELECT CASE WHEN COUNT(*)=0 THEN 'All Null Valued are Handled' ELSE 'There are N...]
24-02-15 15:58:42 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:58:42 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
24-02-15 15:58:42 - root - INFO - All Null Valued are Handled
24-02-15 15:58:42 - snowflake.connector.cursor - INFO - query: [SELECT CASE WHEN COUNT(*) = 0 THEN 'All keys in payloads are in snake case' ELSE...]
24-02-15 15:58:43 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:58:43 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1
24-02-15 15:58:43 - root - INFO - All keys in payloads are in snake case
24-02-15 15:58:43 - snowflake.connector.cursor - INFO - query: [select REGEXP_REPLACE(CAST(payload:start_datetime as date),'-','')as date_callca...]
24-02-15 15:58:43 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:58:43 - snowflake.connector.cursor - INFO - Number of results in first chunk: 0
24-02-15 15:58:43 - root - INFO - Date Id Validation Successful
24-02-15 15:58:43 - snowflake.connector.cursor - INFO - query: [SELECT RPAD(TO_CHAR(payload:start_datetime::TIMESTAMP, 'HH24'), 6, '0') AS hour_...]
24-02-15 15:58:44 - snowflake.connector.cursor - INFO - query execution done
24-02-15 15:58:44 - snowflake.connector.cursor - INFO - Number of results in first chunk: 0
24-02-15 15:58:44 - root - INFO - Hour Id Validation Successful
24-02-15 15:58:45 - root - INFO - Slack notification sent successfully!
24-02-15 15:58:45 - root - INFO - Callcap Data Successfully loaded to Snowflake and Validated
24-02-15 15:58:45 - snowflake.connector.connection - INFO - closed
24-02-15 15:58:45 - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session
24-02-15 15:58:45 - snowflake.connector.connection - INFO - closed
24-02-15 15:58:45 - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session
